config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: redirect('/admin')

  namespace :admin do
    root to: "users#index"

    resources :users
    resources :reports,  only: [:index, :show, :destroy]
    resources :contacts, only: [:index, :show, :destroy]
  end
end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blocked_email.rb
class BlockedEmail < ApplicationRecord
end

app/models/blocked_user.rb
class BlockedUser < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/conversation_notification.rb
class ConversationNotification < ApplicationRecord
end

app/models/email_preference.rb
class EmailPreference < ApplicationRecord
end

app/models/gallery.rb
class Gallery < ApplicationRecord
  has_many :pictures, dependent: :destroy
end

app/models/oauth_access_token.rb
class OauthAccessToken < ApplicationRecord
end

app/models/picture.rb
class Picture < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/search_criterium.rb
class SearchCriterium < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable
  paginates_per 50

  has_one  :about,                      dependent: :destroy
  has_one  :user_detail,                dependent: :destroy
  has_one  :email_preference,           dependent: :destroy
  has_one  :gallery,                    dependent: :destroy
  has_many :reports,                    dependent: :destroy
  has_many :search_criteria,            dependent: :destroy
  has_many :vote_notifications,         dependent: :destroy
  has_many :blocked_users,              dependent: :destroy
  has_many :pictures, through: :gallery
  has_many :oauth_access_tokens,
           foreign_key: :resource_owner_id,
           dependent: :delete_all

  accepts_nested_attributes_for :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
end

app/models/vote_notification.rb
class VoteNotification < ApplicationRecord
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/admin/contacts_controller.rb
module Admin
  class ContactsController < ApplicationController
    def index

    end
  end
end

app/controllers/admin/reports_controller.rb
module Admin
  class ReportsController < Admin::ApplicationController
    def index

    end
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    before_action :set_user, only: [:edit, :show, :update]

    def index
      username = params[:query]
      if username
        users = User.where("username LIKE ?", "%#{username}%")
      else
        users = User.all
      end

      @users = users.page(params[:page]).order(id: :desc)
    end

    def update
      if @user.update(user_params)
        redirect_to admin_user_path(@user), notice: "Updated"
      else
        redirect_to admin_user_path(@user), alert: @user.errors.full_messages
      end
    end

    def destroy
      user = User.find_by(id: params[:id])
      add_user_to_block_list(user)
      user.destroy
      flash['success'] = 'User has been destroyed'
      redirect_to admin_users_path
    end

    private

    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(
        :query,
        :username,
        :email,
        user_detail_attributes: [
          :id,
          :gender,
          :state,
          :age
        ]
      )
    end

    def add_user_to_block_list(user)
      BlockedEmail.create(email: user.email)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def create
    super do
      sign_out(resource) unless resource.admin?
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_messages.html.erb
<strong>Messages</strong>

app/views/admin/users/edit.html.erb
<h1>Edit <%= @user.username %></h1>

<%= form_for [:admin, @user] do |f| %>
  <div class='form-group'>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class='form-group'>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <%= f.fields_for :user_detail do |f| %>
    <div class='form-group'>
      <%= f.label :gender %>
      <%= f.text_field :gender %>
    </div>

    <div class='form-group'>
      <%= f.label :age %>
      <%= f.text_field :age %>
    </div>

    <div class='form-group'>
      <%= f.label :state %>
      <%= f.text_field :state %>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.submit "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<%= form_tag admin_users_path, method: :get do %>
  <%= label_tag :query, "Search for Username:" %>
  <%= text_field_tag :query, params[:query] %>
  <%= submit_tag "Search" %>
<% end %>

<table class='table'>
  <tr>
    <th>ID</th>
    <th>Username</th>
    <th>Email</th>
    <th>Created At</th>
    <th>Action</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at %></td>
      <td><%= link_to 'show', admin_user_path(user) %></td>
      <td><%= link_to 'delete and block', admin_user_path(user), method: :delete %></td>
    </tr>
  <% end %>
</table>
<%= paginate @users %>

app/views/admin/users/show.html.erb
<h1> <%= @user.username %> </h1>
<%= button_to 'Edit', edit_admin_user_path(@user), class: 'btn btn-primary', method: :get %>
<strong>Details</strong>

<table class='table table-bordered'>
  <tr>
    <td><strong>ID</strong></td>
    <td><%= @user.id %></td>
  </tr>
  <tr>
    <td><strong>username</strong></td>
    <td><%= @user.username %></td>
  </tr>
  <tr>
    <td><strong>Email</strong></td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td><strong>Online?</strong></td>
    <td><%= @user.is_signed_in %></td>
  </tr>
  <tr>
    <td><strong>Created At</strong></td>
    <td><%= @user.created_at %></td>
  </tr>
  <tr>
    <td><strong>Gender</strong></td>
    <td><%= @user.user_detail.gender %></td>
  </tr>
  <tr>
    <td><strong>Age</strong></td>
    <td><%= @user.user_detail.age %></td>
  </tr>
  <tr>
    <td><strong>State</strong></td>
    <td><%= @user.user_detail.state %></td>
  </tr>
</table>
<%= render 'messages', user: @user %>